spring:
  application:
    name: dog-service
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        sources:
        - name: ${spring.application.name}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false


#Logging configuration
logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG
    io.github.resilience4j: DEBUG

#Actuator endpoints
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
  server:
    port: 8081